const mongoose=require('mongoose');
const eventSchema=new mongoose.Schema({
    title:{
        type:String,
        required:true,
    },
    description:{
        type:String,
        required:true,
    },
    date:{
        type:String,
        required:true,
    },
    time:{
        type:String,
        required:true,

    },
    location:{
        type:String,
        required:true,
    },
    organizer:{
        type:String,
        required:true,
    },
    price:{
        type:Number,
        required:true,
    },
    totalSeats:{
        type:Number,
        required:true,
    },
    availableSeats:{
        type:Number,
        required:true,
    },
    image:{
        type:String,
        required:true,
    },
    eventType:{
        type:String,
        required:true,
    },
    participants:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
    }],
    bookings:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Booking",
    }],
})

const eventModel=mongoose.model("Events",eventSchema);
module.exports=eventModel;